#ifndef MOTOR_H_
#define MOTOR_H_

#include "main.h"
#include "stm32f1xx_hal.h"
#include "tim.h"
#define AIN1L_HIGH() HAL_GPIO_WritePin(AIN1L_GPIO_Port,AIN1L_Pin,GPIO_PIN_SET)
#define AIN1L_LOW() HAL_GPIO_WritePin(AIN1L_GPIO_Port,AIN1L_Pin,GPIO_PIN_RESET)
#define AIN2L_HIGH() HAL_GPIO_WritePin(AIN2L_GPIO_Port,AIN2L_Pin,GPIO_PIN_SET)
#define AIN2L_LOW() HAL_GPIO_WritePin(AIN2L_GPIO_Port,AIN2L_Pin,GPIO_PIN_RESET)
#define BIN1L_HIGH() HAL_GPIO_WritePin(BIN1L_GPIO_Port,BIN1L_Pin,GPIO_PIN_SET)
#define BIN1L_LOW() HAL_GPIO_WritePin(BIN1L_GPIO_Port,BIN1L_Pin,GPIO_PIN_RESET)
#define BIN2L_HIGH() HAL_GPIO_WritePin(BIN2L_GPIO_Port,BIN2L_Pin,GPIO_PIN_SET)
#define BIN2L_LOW() HAL_GPIO_WritePin(BIN2L_GPIO_Port,BIN2L_Pin,GPIO_PIN_RESET)
#define AIN1R_HIGH() HAL_GPIO_WritePin(AIN1R_GPIO_Port,AIN1R_Pin,GPIO_PIN_SET)
#define AIN1R_LOW() HAL_GPIO_WritePin(AIN1R_GPIO_Port,AIN1R_Pin,GPIO_PIN_RESET)
#define AIN2R_HIGH() HAL_GPIO_WritePin(AIN2R_GPIO_Port,AIN2R_Pin,GPIO_PIN_SET)
#define AIN2R_LOW() HAL_GPIO_WritePin(AIN2R_GPIO_Port,AIN2R_Pin,GPIO_PIN_RESET)
#define BIN1R_HIGH() HAL_GPIO_WritePin(BIN1R_GPIO_Port,BIN1R_Pin,GPIO_PIN_SET)
#define BIN1R_LOW() HAL_GPIO_WritePin(BIN1R_GPIO_Port,BIN1R_Pin,GPIO_PIN_RESET)
#define BIN2R_HIGH() HAL_GPIO_WritePin(BIN2R_GPIO_Port,BIN2R_Pin,GPIO_PIN_SET)
#define BIN2R_LOW() HAL_GPIO_WritePin(BIN2R_GPIO_Port,BIN2R_Pin,GPIO_PIN_RESET)
void MOTOR_init(void);
void MOTOR_Speed(int left_speed, int right_speed);
#endif //MOTOR_H